services:
  mysql:
    image: mysql:8.4
    container_name: medicare360-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicare360
    ports:
      - "3306:3306"
    volumes:
      - medicare360-db:/var/lib/mysql
volumes:
  medicare360-db:
